baseURL = "https://fitmath.github.io/"
languageCode = "en-us"
title = "FIT Math"
theme = "FITMathMinimal"
author = "Jonathan Goldfarb"

[params]
    font = "Raleway" # should match the name on Google Fonts!
